import { useLocation } from "react-router";

import ReactMarkdown from "react-markdown";
function Response() {
  const location = useLocation();

  const result = location.state?.result;
  console.log("result here ", result);
  return (
    <main className="min-h-screen bg-[#fafaff] px-6 py-12">
      <div className="mx-auto max-w-4xl">
        <h1 className="mb-8 text-3xl font-bold text-[#11152f]">
          Interview Analysis
        </h1>

        <div className="rounded-2xl border border-gray-100 bg-white p-8 shadow-[0_10px_50px_rgba(60,70,130,0.08)]">
          <ReactMarkdown
            components={{
              h2: ({ children }) => (
                <h2 className="mb-5 mt-10 text-2xl font-bold tracking-tight text-[#11152f]">
                  {children}
                </h2>
              ),

              h3: ({ children }) => (
                <h3 className="mb-4 mt-7 text-lg font-bold text-[#11152f]">
                  {children}
                </h3>
              ),

              p: ({ children }) => (
                <p className="mb-3 text-[15px] leading-7 text-gray-700">
                  {children}
                </p>
              ),

              strong: ({ children }) => (
                <strong className="font-bold text-[#11152f]">{children}</strong>
              ),

              ul: ({ children }) => (
                <ul className="mb-5 list-disc space-y-2 pl-6 text-[15px] text-gray-700">
                  {children}
                </ul>
              ),

              ol: ({ children }) => (
                <ol className="mb-5 list-decimal space-y-2 pl-6 text-[15px] text-gray-700">
                  {children}
                </ol>
              ),

              li: ({ children }) => <li className="leading-7">{children}</li>,

              hr: () => (
                <hr className="my-8 border-0 border-t border-gray-200" />
              ),
            }}
          >
            {result}
          </ReactMarkdown>
        </div>
      </div>
    </main>
  );
}

export default Response;

// <main className="min-h-screen bg-[#fafaff] text-[#11152f]">
//   {/* Navbar */}
//   <nav className="border-b border-gray-100 bg-white">
//     <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
//       {/* Logo */}
//       <div className="flex items-center gap-2.5">
//         <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-500 to-purple-500 text-lg text-white">
//           ✦
//         </div>

//         <span className="text-lg font-bold">InterviewAI</span>
//       </div>

//       {/* Navigation */}
//       <div className="hidden items-center gap-8 text-sm font-medium text-gray-500 md:flex">
//         <a href="/" className="transition hover:text-[#11152f]">
//           Home
//         </a>

//         <a href="/how-it-works" className="transition hover:text-[#11152f]">
//           How it works
//         </a>

//         <a href="/features" className="transition hover:text-[#11152f]">
//           Features
//         </a>
//       </div>

//       <button className="rounded-lg bg-[#11152f] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#252a4a]">
//         Analyze Interview
//       </button>
//     </div>
//   </nav>

//   {/* Page heading */}
//   <section className="px-6 pb-8 pt-14 text-center">
//     <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-purple-200 bg-purple-50 px-4 py-1.5 text-xs font-semibold tracking-wide text-purple-600">
//       <span>✦</span>
//       ANALYSIS COMPLETE
//     </div>

//     <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
//       Your Interview Review
//     </h1>

//     <p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-gray-500">
//       Detailed AI-generated feedback based on your interview transcript.
//     </p>
//   </section>

//   {/* Result Container */}
//   <section className="mx-auto max-w-4xl px-6 pb-10">
//     <div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-[0_10px_50px_rgba(60,70,130,0.08)]">
//       {/* Result header */}
//       <div className="flex items-center justify-between border-b border-gray-100 px-7 py-5">
//         <div>
//           <h2 className="text-base font-semibold">Interview Analysis</h2>

//           <p className="mt-1 text-xs text-gray-400">
//             Generated by InterviewAI
//           </p>
//         </div>

//         <button className="flex items-center gap-2 rounded-lg border border-gray-200 px-4 py-2 text-xs font-semibold text-gray-500 transition hover:border-purple-200 hover:bg-purple-50 hover:text-purple-600">
//           <span>▣</span>
//           Copy
//         </button>
//       </div>

//       {/* AI Response */}
//       <article className="px-7 py-8 md:px-10 md:py-10">
//         {/* Summary */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">1. Interview Summary</h2>

//           <div className="space-y-3 text-sm leading-7 text-gray-600">
//             <p>
//               <span className="font-semibold text-[#11152f]">
//                 Type of Interview:
//               </span>{" "}
//               Backend Technical Screening
//             </p>

//             <p>
//               <span className="font-semibold text-[#11152f]">
//                 Main Topics:
//               </span>{" "}
//               Node.js, Express, MongoDB, Redis, Socket.IO and backend
//               fundamentals.
//             </p>

//             <p>
//               The candidate demonstrated a reasonable understanding of
//               backend development concepts. Most answers were correct,
//               although several responses lacked technical depth.
//             </p>
//           </div>
//         </section>

//         <div className="my-8 border-t border-gray-100" />

//         {/* Technical */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">
//             2. Technical Performance
//           </h2>

//           <div className="space-y-4 text-sm leading-7 text-gray-600">
//             <p>
//               The candidate correctly explained Node.js as a JavaScript
//               runtime built on Chrome's V8 engine and demonstrated an
//               understanding of the event loop.
//             </p>

//             <p>
//               However, the explanation of Node.js being single-threaded was
//               somewhat oversimplified. The response could have included
//               details about libuv, asynchronous I/O and the worker pool.
//             </p>

//             {/* Score */}
//             <div className="mt-5 rounded-xl border border-purple-100 bg-purple-50/60 p-4">
//               <div className="flex items-center justify-between">
//                 <span className="font-semibold text-[#11152f]">
//                   Technical Score
//                 </span>

//                 <span className="text-lg font-bold text-purple-600">
//                   6/10
//                 </span>
//               </div>
//             </div>
//           </div>
//         </section>

//         <div className="my-8 border-t border-gray-100" />

//         {/* Behavioral */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">
//             3. Behavioral Performance
//           </h2>

//           <div className="space-y-4 text-sm leading-7 text-gray-600">
//             <p>
//               The candidate provided a concrete example of debugging a
//               Socket.IO room issue and explained how the problem was
//               resolved.
//             </p>

//             <p>
//               The answer could be improved by providing more context,
//               explaining the debugging process in greater detail and clearly
//               describing the final outcome.
//             </p>

//             <div className="mt-5 rounded-xl border border-purple-100 bg-purple-50/60 p-4">
//               <div className="flex items-center justify-between">
//                 <span className="font-semibold text-[#11152f]">
//                   Behavioral Score
//                 </span>

//                 <span className="text-lg font-bold text-purple-600">
//                   5/10
//                 </span>
//               </div>
//             </div>
//           </div>
//         </section>

//         <div className="my-8 border-t border-gray-100" />

//         {/* Communication */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">4. Communication</h2>

//           <div className="space-y-4 text-sm leading-7 text-gray-600">
//             <p>
//               The candidate communicated ideas clearly overall, but
//               frequently used filler words such as{" "}
//               <span className="font-medium text-[#11152f]">
//                 "umm", "yeah", "like"
//               </span>{" "}
//               and{" "}
//               <span className="font-medium text-[#11152f]">"I guess".</span>
//             </p>

//             <p>
//               Answers were generally concise and understandable, although
//               more structured explanations would improve overall delivery.
//             </p>

//             <div className="mt-5 rounded-xl border border-purple-100 bg-purple-50/60 p-4">
//               <div className="flex items-center justify-between">
//                 <span className="font-semibold text-[#11152f]">
//                   Communication Score
//                 </span>

//                 <span className="text-lg font-bold text-purple-600">
//                   5/10
//                 </span>
//               </div>
//             </div>
//           </div>
//         </section>

//         <div className="my-8 border-t border-gray-100" />

//         {/* Topics */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">
//             5. Topics & Technologies
//           </h2>

//           <div className="flex flex-wrap gap-2">
//             {[
//               "Node.js",
//               "Express",
//               "MongoDB",
//               "Redis",
//               "Socket.IO",
//               "REST APIs",
//               "Event Loop",
//               "Authentication",
//               "Authorization",
//               "Caching",
//             ].map((topic) => (
//               <span
//                 key={topic}
//                 className="rounded-full border border-gray-200 bg-gray-50 px-3 py-1.5 text-xs font-medium text-gray-600"
//               >
//                 {topic}
//               </span>
//             ))}
//           </div>
//         </section>

//         <div className="my-8 border-t border-gray-100" />

//         {/* Overall Assessment */}
//         <section>
//           <h2 className="mb-5 text-xl font-bold">Overall Assessment</h2>

//           <p className="text-sm leading-7 text-gray-600">
//             The candidate demonstrates a good foundation in backend
//             development and practical experience with Node.js, Redis,
//             MongoDB and Socket.IO. The biggest area for improvement is
//             technical depth, particularly when explaining how technologies
//             work internally.
//           </p>

//           {/* Overall score */}
//           <div className="mt-6 rounded-xl bg-[#11152f] p-5 text-white">
//             <div className="flex items-center justify-between">
//               <div>
//                 <p className="font-semibold">Overall Score</p>
//                 <p className="mt-1 text-xs text-white/50">
//                   Based on the provided transcript
//                 </p>
//               </div>

//               <span className="text-3xl font-bold">6/10</span>
//             </div>
//           </div>
//         </section>
//       </article>
//     </div>

//     {/* Bottom Action */}
//     <div className="mt-8 flex justify-center">
//       <button className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-indigo-500 to-purple-500 px-7 py-3.5 text-sm font-semibold text-white shadow-lg shadow-purple-200 transition hover:opacity-90">
//         <span>✦</span>
//         Analyze Another Interview
//       </button>
//     </div>

//     {/* Disclaimer */}
//     <p className="mx-auto mt-5 max-w-xl text-center text-xs leading-5 text-gray-400">
//       InterviewAI provides AI-generated feedback for interview preparation.
//       Results may not always be accurate and should be used as guidance.
//     </p>
//   </section>
// </main>
